import { Inter, Lato } from "next/font/google";
import "./globals.css";
import FirstNav from "@/components/FirstNav";
import SecondNav from "@/components/SecondNav";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const lato = Lato({
	subsets: ["latin-ext"],
	weight: ["400", "700"], // Specify the weights you want to use
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={lato.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
